import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

// Optional integration check: npm install --no-save playwright, then start npm start.
const modulePath = process.env.PLAYWRIGHT_MODULE;
const { chromium } = await import(modulePath ? pathToFileURL(modulePath).href : 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : { channel: 'chrome' }), args: ['--enable-webgl', '--ignore-gpu-blocklist', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const base = process.env.BASE_URL || 'http://127.0.0.1:4173';
const output = 'test-results';
await mkdir(output, { recursive: true });
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 400 && response.url().startsWith(base)) errors.push(`${response.status()} ${response.url()}`); });
try {
  await page.goto(`${base}/games/castlestrike/`);
  await page.waitForFunction(() => window.castleStrike?.state?.status === 'preparation');
  await page.locator('.unit-card').first().waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.waitForFunction(() => castleStrike.battlefield.renderer?.info.render.frame > 2);
  await page.waitForTimeout(350);
  await page.screenshot({ path: `${output}/castle-strike-desktop.png`, fullPage: true });
  assert.equal(await page.locator('.unit-card').count(), 9);
  assert.equal(await page.evaluate(() => !!window.castleStrike.battlefield.renderer), true, 'WebGL renderer starts');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal page overflow');
  const initial = await page.evaluate(() => ({ gold: castleStrike.state.gold, count: castleStrike.state.roster.length }));
  await page.locator('[data-recruit="footman"]').click();
  assert.equal(await page.evaluate(() => castleStrike.state.roster.length), initial.count + 1);
  assert.equal(await page.evaluate(() => castleStrike.state.gold), initial.gold - 100);
  await page.locator('[data-inspect="archer"]').click();
  assert.match(await page.locator('#unit-detail').textContent(), /Silverleaf/);
  await page.getByRole('tab', { name: 'Formation' }).click();
  await page.locator('[data-cell="2,4"]').click();
  await page.locator('[data-cell="0,0"]').click();
  assert.equal(await page.evaluate(() => castleStrike.state.roster[0].row), 0);
  assert.equal(await page.evaluate(() => castleStrike.state.roster[0].col), 0);
  await page.getByRole('tab', { name: 'Research' }).click();
  await page.locator('[data-research="mines"]').click();
  assert.equal(await page.evaluate(() => castleStrike.state.mineLevel), 1);
  await page.getByRole('tab', { name: 'Scout' }).click();
  assert.equal(await page.locator('.scout-unit').count(), 3);
  await page.getByRole('tab', { name: 'Recruit' }).click();
  await page.locator('#play-btn').click();
  await page.waitForFunction(() => castleStrike.state.units.length > 0);
  await page.keyboard.press('Space');
  assert.equal(await page.evaluate(() => castleStrike.state.paused), true);
  await page.locator('#resume-btn').click();
  await page.locator('[data-speed="2"]').click();
  assert.equal(await page.evaluate(() => castleStrike.state.speed), 2);
  await page.evaluate(() => { castleStrike.game.update(22); });
  await page.waitForFunction(() => castleStrike.state.time >= 22);
  await page.locator('[data-spell="meteor"]').click();
  await page.locator('#cast-prompt').waitFor({ state: 'visible' });
  assert.equal(await page.evaluate(() => castleStrike.battlefield.targeting?.id), 'meteor');
  await page.keyboard.press('Escape');
  await page.locator('#cast-prompt').waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => castleStrike.battlefield.targeting), null);
  await page.locator('#help-btn').click();
  assert.equal(await page.evaluate(() => castleStrike.state.paused), true, 'Opening help pauses combat');
  await page.getByRole('button', { name: 'My army awaits' }).click();
  // Native dialog close events resume combat asynchronously.
  await page.waitForFunction(() => castleStrike.state.paused === false);
  assert.equal(await page.evaluate(() => castleStrike.state.paused), false, 'Closing help resumes combat');
  await page.evaluate(() => { castleStrike.game.togglePause(); castleStrike.save(); });
  const saved = await page.evaluate(() => ({ wave: castleStrike.state.wave, count: castleStrike.state.roster.length, gold: castleStrike.state.gold }));
  await page.reload();
  await page.waitForFunction(() => !!window.castleStrike);
  assert.equal(await page.evaluate(() => castleStrike.state.paused), true);
  assert.deepEqual(await page.evaluate(() => ({ wave: castleStrike.state.wave, count: castleStrike.state.roster.length, gold: castleStrike.state.gold })), saved);
  await page.locator('#settings-btn').click();
  await page.locator('[data-faction="undead"]').click();
  await page.locator('#difficulty-select').selectOption('hard');
  await page.locator('#new-match-btn').click();
  assert.equal(await page.evaluate(() => castleStrike.state.faction), 'undead');
  assert.equal(await page.evaluate(() => castleStrike.state.status), 'preparation');
  assert.equal(await page.locator('.unit-card').count(), 9);
  await page.locator('#play-btn').click();
  // Advance a budget-constrained mixed army; this also exercises mid-battle UI updates.
  await page.evaluate(async () => {
    const { UNITS } = await import('/games/castlestrike/src/data.js');
    const g=castleStrike.game;
    for(let i=0;i<24 && g.state.status==='playing';i++){
      g.update(5);
      if(g.state.tier<2 && g.state.gold>=g.getResearchCost('tier'))g.research('tier');
      if(g.state.supply>=g.state.supplyCap-4 && g.state.gold>=g.getResearchCost('barracks'))g.research('barracks');
      const types=UNITS.filter(u=>u.faction===g.state.faction&&u.tier<=g.state.tier);
      g.recruit(types[i%types.length].id);
    }
    g.update(8);
  });
  await page.waitForTimeout(300);
  await page.locator('#wave-announcement').waitFor({ state: 'hidden' });
  await page.locator('#toast').waitFor({ state: 'hidden' });
  await page.screenshot({ path: `${output}/castle-strike-battle.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => castleStrike.battlefield.resetCamera());
  await page.waitForTimeout(250);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No mobile horizontal overflow');
  assert.equal(await page.locator('#mobile-play-btn').isVisible(), true, 'Mobile battle control stays reachable');
  await page.screenshot({ path: `${output}/castle-strike-mobile.png`, fullPage: true });
  await page.locator('#settings-btn').click();
  await page.locator('#quality-select').selectOption('low');
  await page.locator('#settings-dialog [data-close]').click();
  assert.equal(await page.evaluate(() => castleStrike.battlefield.quality), 'low');
  assert.deepEqual(errors, [], 'No page errors or missing local assets');
  console.log('PASS: desktop/mobile layout, 3D rendering, recruit/inspect, formation, research, scouting, pause/resume, spells, help, save/reload, faction restart, speed, low quality.');
} finally { await browser.close(); }
